Store/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Brand
    {
        [Key]
        public int BrandId { get; set; }
        [Required]
        [StringLength(50)]
        public string BrandName { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}

Store/Areas/Admin/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Models;

namespace Store.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandsController : Controller
    {
        private readonly StoreContext _context;

        public BrandsController(StoreContext context)
        {
            _context = context;
        }

        // GET: Admin/Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Admin/Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Admin/Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandId,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Admin/Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Admin/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrandId,BrandName")] Brand brand)
        {
            if (id != brand.BrandId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Admin/Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Admin/Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            if (brand != null)
            {
                _context.Brands.Remove(brand);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandId == id);
        }
    }
}

Store/Areas/Admin/Views/Brands/Create.cshtml
@model Store.Models.Brand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Admin" asp-controller="Brands" asp-action="Index">Back to List</a>
</div>

Store/Areas/Admin/Views/Brands/Delete.cshtml
@model Store.Models.Brand

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BrandId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="Admin" asp-controller="Brands" asp-action="Index">Back to List</a>
    </form>
</div>

Store/Areas/Admin/Views/Brands/Details.cshtml
@model Store.Models.Brand

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Admin" asp-controller="Brands" asp-action="Edit" asp-route-id="@Model?.BrandId">Edit</a> |
    <a asp-area="Admin" asp-controller="Brands" asp-action="Index">Back to List</a>
</div>

Store/Areas/Admin/Views/Brands/Edit.cshtml
@model Store.Models.Brand

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BrandId" />
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Admin" asp-controller="Brands" asp-action="Index">Back to List</a>
</div>

Store/Areas/Admin/Views/Brands/Index.cshtml
@model IEnumerable<Store.Models.Brand>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Brand Manager</h1>

<p>
    <a asp-area="Admin" asp-controller="Brands" asp-action="Create" class="w3-button w3-green">Create New</a>
</p>

<div class="w3-container">
    <table class="w3-table-all w3-hoverable">
        <thead>
            <tr class="w3-light-grey">
                <th>@Html.DisplayNameFor(model => model.BrandName)</th>
                <th>Actions</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.BrandName)</td>
                <td>
                    <a asp-area="Admin" asp-controller="Brands" asp-action="Edit" asp-route-id="@item.BrandId">Edit</a> |
                    <a asp-area="Admin" asp-controller="Brands" asp-action="Details" asp-route-id="@item.BrandId">Details</a> |
                    <a asp-area="Admin" asp-controller="Brands" asp-action="Delete" asp-route-id="@item.BrandId">Delete</a>
                </td>
            </tr>
        }

    </table>
</div>